# Generated by Django 2.1.5 on 2019-02-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='É Vendedor ??'),
        ),
    ]
