# Generated by Django 2.1.5 on 2019-02-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preço'),
        ),
    ]
